client bng1 {
    ipaddr = 10.99.1.2
    secret = testlab123
    require_message_authenticator = no
    limit_proxy_state = no
}
client bng2 {
    ipaddr = 10.99.1.3
    secret = testlab123
    require_message_authenticator = no
    limit_proxy_state = no
}
