---
# Ansible inventory 


all:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_host_key_checking: false

  children:
    sros:
      vars:
        ansible_network_os: nokia.sros.classic
        ansible_user: "{{ lookup('env', 'SROS_USERNAME') | default('admin', true) }}"
        ansible_password: "{{ lookup('env', 'SROS_PASSWORD') | default('lab123', true) }}"
      hosts:
        bngmaster:
          ansible_host: 10.99.1.2
        bngslave:
          ansible_host: 10.99.1.3

    srlinux:
      vars:
        ansible_network_os: nokia.srlinux.srlinux
        ansible_user: "{{ lookup('env', 'SRL_USERNAME') | default('admin', true) }}"
        ansible_password: "{{ lookup('env', 'SRL_PASSWORD') | default('NokiaSrl1!', true) }}"
      hosts:
        olt:
          ansible_host: 10.99.1.4
        carrier1:
          ansible_host: 10.99.1.252
        carrier2:
          ansible_host: 10.99.1.253

    linux:
      vars:
        ansible_connection: ssh
        ansible_user: "{{ lookup('env', 'LINUX_USERNAME') | default('root', true) }}"
        ansible_password: "{{ lookup('env', 'LINUX_PASSWORD') | default('test', true) }}"
        ansible_become: false
      hosts:
        ont1:
          ansible_host: 10.99.1.5
        pc1:
          ansible_host: 10.99.1.7
        radius:
          ansible_host: 10.99.1.8
        dns:
          ansible_host: 10.99.1.13
        gateway:
          ansible_host: 10.99.1.14
        lig:
          ansible_host: 10.99.1.12

    telemetry:
      vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_password: ""
      hosts:
        gnmic:
          ansible_host: 10.99.1.9
        prometheus:
          ansible_host: 10.99.1.10
        grafana:
          ansible_host: 10.99.1.11

    bngs:
      children:
        sros: {}

    carriers:
      hosts:
        carrier1: {}
        carrier2: {}
