// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const locale = process.env.DOCUSAURUS_CURRENT_LOCALE || 'es';
const isEn = locale === 'en';

const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: isEn ? '🏠 Home' : '🏠 Inicio',
    },
    {
      type: 'category',
      label: isEn ? '🗺️ Topology' : '🗺️ Topología',
      items: [{ type: 'autogenerated', dirName: 'topologia' }],
    },
    {
      type: 'category',
      label: '🧩 MOPT',
      items: [{ type: 'autogenerated', dirName: 'mopt' }],
    },
    {
      type: 'category',
      label: isEn ? '📡 Telemetry' : '📡 Telemetría',
      items: [{ type: 'autogenerated', dirName: 'telemetria' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '📜 LOGs',
      items: [{ type: 'autogenerated', dirName: 'logs' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🔐 RADIUS / AAA',
      items: [{ type: 'autogenerated', dirName: 'radius' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🕵️ LEA Console',
      items: [{ type: 'autogenerated', dirName: 'lea-console' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🤖 Containerbot',
      items: [{ type: 'autogenerated', dirName: 'containerbot' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🛠️ Operación',
      items: [{ type: 'autogenerated', dirName: 'operacion' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: '🧪 ATP',
      items: [{ type: 'autogenerated', dirName: 'atp' }],
      collapsed: true,
    },
    {
      type: 'category',
      label: isEn ? '🚀 Deploy' : '🚀 Despliegue',
      items: [{ type: 'autogenerated', dirName: 'despliegue' }],
      collapsed: true,
    },
  ],
};

module.exports = sidebars;
